---
- name: Deploy DocuSeal service
  hosts: servers
  become: yes
  tasks:
    - name: Ensure Docker Compose is installed
      shell: |
        if [ ! -f /usr/local/bin/docker-compose ]; then
          curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
        fi

    - name: Create DocuSeal Docker Compose directory
      file:
        path: /srv/compose/docuseal
        state: directory
        mode: '0755'

    - name: Deploy DocuSeal Docker Compose configuration
      copy:
        dest: /srv/compose/docuseal/docker-compose.yml
        content: |
          version: '3'

          services:
            app:
              image: docuseal/docuseal:latest
              ports:
                - "3555:3000"
              volumes:
                - /bhdata/DOCKER/lhldocuseal/data:/data
              environment:
                - DATABASE_URL=postgresql://docuseal:Q4peVDVDq-FD@10.27.112.218:5432/docusealdb
                - HOST=docuseal.linuxhomelabs.net

    - name: Start DocuSeal service using Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /srv/compose/docuseal/
      register: compose_up_result
      failed_when: compose_up_result.rc != 0
      retries: 3
      delay: 5
      until: compose_up_result.rc == 0

    - name: Verify DocuSeal service is running
      shell: docker ps | grep docuseal
      register: docuseal_status
      failed_when: "docuseal_status.stdout == ''"
