---
- name: Deploy Docker Compose configuration for Watchtower
  hosts: servers
  become: yes

  tasks:
    - name: Ensure the /srv/compose/ directory exists
      file:
        path: /srv/compose/
        state: directory
        mode: '0755'

    - name: Copy Docker Compose file to the target directory
      copy:
        dest: /srv/compose/watchtower-compose.yml
        content: |
          version: "3"

          services:
            watchtower:
              container_name: watchtower
              restart: always
              environment:
                WATCHTOWER_SCHEDULE: 30 4 * * *
                TZ: America/Los_Angeles
                WATCHTOWER_CLEANUP: "true"
                WATCHTOWER_DEBUG: "true"
                WATCHTOWER_NOTIFICATIONS: email
                WATCHTOWER_NOTIFICATION_EMAIL_FROM: evan@evanwilliammiller.com
                WATCHTOWER_NOTIFICATION_EMAIL_TO: evan@certifiedmactech.com
                WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
                WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 465
                WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: evan@evanwilliammiller.com
                WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: qvpirlgkglnlojeu

              image: containrrr/watchtower
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                containrrr/watchtower --privileged

    - name: Run Docker Compose up
      shell: docker-compose -f /srv/compose/watchtower-compose.yml up -d
      args:
        chdir: /srv/compose/
