---
- name: Wazuh agent installation and configuration
  hosts: all
  become: yes
  tasks:

    - name: Map IP addresses to hostnames
      set_fact:
        hostname_mapping:
          10.27.112.10: "LHLGhost"
          10.27.112.11: "LHLHelpdesk"
          10.27.112.12: "LHLLeantime"
          10.27.112.14: "LHLRedmine"
          10.27.112.33: "LHLInvoiceninja"
          10.27.112.233: "watchyourlan"
          10.27.112.17: "bhextcloud"

    - name: Set the correct hostname using hostnamectl
      command: hostnamectl set-hostname "{{ hostname_mapping[ansible_host] }}"

    - name: Update /etc/hostname with the correct hostname
      copy:
        content: "{{ hostname_mapping[ansible_host] }}\n"
        dest: /etc/hostname

    - name: Ensure /etc/hosts has the correct hostname
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 {{ hostname_mapping[ansible_host] }}"
        state: present

    - name: Reboot the server to apply hostname changes
      reboot:
        reboot_timeout: 300

    - name: Verify hostname is set correctly
      command: hostname
      register: hostname_output

    - name: Assert hostname matches expected value
      assert:
        that:
          - hostname_output.stdout == hostname_mapping[ansible_host]
        fail_msg: "Hostname does not match expected value {{ hostname_mapping[ansible_host] }}."
        success_msg: "Hostname is correctly set to {{ hostname_mapping[ansible_host] }}."

    - name: Download Wazuh agent
      shell: wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.11.0-1_amd64.deb
      args:
        executable: /bin/bash

    - name: Validate the Wazuh agent package
      stat:
        path: wazuh-agent_4.11.0-1_amd64.deb
      register: wazuh_agent_deb_stat

    - name: Fail if Wazuh agent download failed
      fail:
        msg: "Wazuh agent download failed. The .deb file is not valid."
      when: wazuh_agent_deb_stat.stat.size < 1024

    - name: Install Wazuh agent
      shell: WAZUH_MANAGER='10.27.112.225' WAZUH_AGENT_NAME='{{ hostname_mapping[ansible_host] }}' dpkg -i ./wazuh-agent_4.11.0-1_amd64.deb
      args:
        executable: /bin/bash
      register: wazuh_install
      changed_when: "'WAZUH_AGENT_NAME' in wazuh_install.stdout"

    - name: Reload systemd daemon
      shell: systemctl daemon-reload

    # ✅ Enable Wazuh agent at boot
    - name: Enable Wazuh agent service
      systemd:
        name: wazuh-agent
        enabled: yes

    # ✅ Start Wazuh agent
    - name: Start Wazuh agent service
      systemd:
        name: wazuh-agent
        state: started

    # ✅ Check if Wazuh agent is running
    - name: Check Wazuh agent status
      shell: systemctl is-active wazuh-agent
      register: wazuh_status
      changed_when: false

    - name: Confirm Wazuh agent is running
      assert:
        that: wazuh_status.stdout == "active"
        fail_msg: "Wazuh agent is NOT running!"
        success_msg: "Wazuh agent is running successfully."