---
- name: Restart Docker on all servers
  hosts: servers
  become: yes
  tasks:
    - name: Restart Docker service
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: yes
