---
- name: Set up Zsh environment for root
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - zsh
          - curl
          - git
        state: present
        update_cache: yes

    - name: Change default shell to zsh for root user
      shell: chsh -s /bin/zsh root

    - name: Check if Oh My Zsh is already installed
      stat:
        path: /root/.oh-my-zsh
      register: oh_my_zsh_installed

    - name: Install Oh My Zsh if not already installed
      shell: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        executable: /bin/bash
      when: not oh_my_zsh_installed.stat.exists

    - name: Install zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: /root/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Install zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /root/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

    - name: Install Atuin
      shell: |
        bash -c "$(curl https://raw.githubusercontent.com/ellie/atuin/main/install.sh)"
      args:
        executable: /bin/bash

    - name: Copy the custom .zshrc file
      copy:
        dest: /root/.zshrc
        content: |
          # If you come from bash you might have to change your $PATH.
          # export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

          # Path to your Oh My Zsh installation.
          export ZSH="$HOME/.oh-my-zsh"

          ZSH_THEME="fino-time"

          plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

          source $ZSH/oh-my-zsh.sh

          . "$HOME/.atuin/bin/env"
          eval "$(atuin init zsh)"
          source ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
